const HOME_DATA_REQUEST = 'HOME_DATA_REQUEST'
const HOME_DATA_SUCCESS = 'HOME_DATA_REQUEST'
const HOME_DATA_FAIL = 'HOME_DATA_REQUEST'
export default {
  HOME_DATA_REQUEST, HOME_DATA_SUCCESS,HOME_DATA_FAIL
}
